FROM alpine:latest AS certs
RUN apk add --no-cache ca-certificates

FROM scratch
ARG TARGETOS
ARG TARGETARCH
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY dist/copilot2api-${TARGETOS}-${TARGETARCH} /copilot2api
ENV HOME=/root
ENV COPILOT2API_HOST=0.0.0.0
ENV COPILOT2API_PORT=7777
EXPOSE 7777 7778
ENTRYPOINT ["/copilot2api"]
