FROM alpine:latest AS certs
RUN apk add --no-cache ca-certificates

FROM scratch
ARG TARGETOS
ARG TARGETARCH
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY dist/copilot2api-${TARGETOS}-${TARGETARCH} /copilot2api
ENV HOME=/root
ENV COPILOT2API_HOST=0.0.0.0
ENV COPILOT2API_PORT=8888
ENV COPILOT2API_ADMIN_HOST=0.0.0.0
ENV COPILOT2API_ADMIN_PORT=8889
EXPOSE 8888 8889
ENTRYPOINT ["/copilot2api"]
